config/routes.rb
Rails.application.routes.draw do
  get 'searches/user'
  get 'searches/tweet'

  # get 'home/index'
  # get 'home/show'
  root 'home#index'
  devise_for :users
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :messages, only: [:create]

  resources :rooms, only: [:create, :show]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # def search(search)
  #   if search
  #     User.where(['name LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end

  # def Tsearch(search)
  #   if search
  #     Tweet.where(['body LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :tweet_id, presence: true
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  default_scope -> {order(created_at: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :following, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(room_id: @room.id, user_id: current_user.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:room_id, :user_id).merge(room_id: @room.id)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :authenticate_user!

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      redirect_to tweets_path
    else
      redirect_to new_tweet_path
    end
  end

  def index
    @tweets = Tweet.all.search(params[:search])
    @tweets = Tweet.page(params[:page]).per(10)
  end

  def show
    @tweet = Tweet.find(params[:id])
    @comment = current_user.comments.build
    @comments = @tweet.comments
  end

  def destroy
    @tweet = Tweet.find_by(user_id: current_user.id)
    @tweet.destroy
    redirect_to tweets_path
  end

  private

    def tweet_params
      params.require(:tweet).permit(:body, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.search(params[:search])
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
    @comments = @user.comments
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def follows
    user = User.find(params[:id])
    @users = user.following
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationsips_helper.rb
module RelationsipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/tweets/index.html.erb
<div class="container color-box">
  <h1>ツイート一覧</h1>

<% @tweets.each do |tweet| %>
  <hr>
  <h5><%= link_to tweet.user.name, user_path(tweet.user.id) %></h5>
  <p>
    <%= link_to tweet.body, tweet_path(tweet.id) %>
  </p>
    <%= image_tag tweet.image.url if tweet.image? %>
    <% if current_user == tweet.user || current_user.admin? %>
      <p><%= link_to "削除する", tweet_path(tweet.id), method: :delete, data: {confirm: "本当に消しますか？"} %></p>
    <% end %>
  <% if tweet.favorited_by?(current_user) %>
    <p>
      <%= link_to tweet_favorites_path(tweet.id), method: :delete do %>
        <i class="fa fa-heart fav-btn"></i><%= tweet.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to tweet_favorites_path(tweet.id), method: :post do %>
        <% if tweet.favorites.count == 0 %>
          <i class="fa fa-heart unfav-btn"></i>
        <% else %>
          <i class="fa fa-heart unfav-btn"></i><%= tweet.favorites.count %>
        <% end %>
      <% end %>
    </p>
  <% end %>
  <% if current_user != tweet.user %>
    <% if tweet.user.followed_by?(current_user) %>
      <p><%=link_to "フォロー中", user_relationships_path(tweet.user.id), method: :delete %></p>
    <% else %>
      <p><%=link_to "フォローする", user_relationships_path(tweet.user.id), method: :post %></p>
    <% end %>
  <% end %>
  <p><span><%= tweet.created_at.strftime("%Y-%m-%d %H:%M") %></span></p>
<% end %>
<%= paginate @tweets %>
</div>

app/views/tweets/new.html.erb
<div class="container col-md-7 new-post">
  <h1>新規投稿</h1>

  <%= form_for @tweet do |f| %>
    <p>
      <%= f.text_area :body %>
      <%= f.file_field :image, class: "textarea" %>
    </p>
    <%= f.submit "投稿する", class: "btn btn-outline-warning" %>
  <% end %>
</div>

app/views/tweets/show.html.erb
<div class="container color-box">
  <h1>ツイート</h1>
  <hr>
  <h5><%= link_to @tweet.user.name, user_path(@tweet.user.id) %></h5>
  <p>
    <%= @tweet.body %>
    <% if current_user == @tweet.user %>
      <%= link_to "削除する", tweet_path(@tweet.id), method: :delete, data: {confirm: "本当に消しますか？"} %>
    <% end %>
  </p>
  <% if @tweet.favorited_by?(current_user) %>
    <p>
      <%= link_to tweet_favorites_path(@tweet.id), method: :delete do %>
        <i class="fa fa-heart fav-btn"></i><%= @tweet.favorites.count %>
      <% end %>
    </p>
  <% else %>
    <p>
      <%= link_to tweet_favorites_path(@tweet.id), method: :post do %>
        <% if @tweet.favorites.count == 0 %>
          <i class="fa fa-heart unfav-btn"></i>
        <% else %>
          <i class="fa fa-heart unfav-btn"></i><%= @tweet.favorites.count %>
        <% end %>
      <% end %>
    </p>
  <% end %>

  <h5>返信</h5>
  <%= form_for([@tweet, @comment]) do |f| %>
    <h5>
      <%= f.label :body, "コメント" %>
      <%= f.text_field :body %>
    </h5>
    <%= f.submit %>
  <% end %>

  <% @comments.each do |comment| %>
    <hr>
    <h6><%= link_to comment.user.name, user_path(comment.user.id) %></h6>
    <p><%= comment.body %></p>
    <% if current_user == comment.user %>
      <%= link_to "削除", tweet_comments_path(comment.tweet.id), method: :delete %>
    <% end %>
  <% end %>
</div>