config/routes.rb
Rails.application.routes.draw do
  get 'searches/user'
  get 'searches/tweet'

  # get 'home/index'
  # get 'home/show'
  root 'home#index'
  devise_for :users
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :messages, only: [:create]

  resources :rooms, only: [:create, :show]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # def search(search)
  #   if search
  #     User.where(['name LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end

  # def Tsearch(search)
  #   if search
  #     Tweet.where(['body LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :tweet_id, presence: true
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  default_scope -> {order(created_at: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :following, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!

  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(entry_params)
    redirect_to room_path(@room.id)
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(room_id: @room.id, user_id: current_user.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private
    def entry_params
      params.require(:entry).permit(:room_id, :user_id).merge(room_id: @room.id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all.search(params[:search])
    @users = User.page(params[:page]).per(10)
  end

  def show
    @user = User.find(params[:id])
    @tweets = @user.tweets
    @favorite_tweets = @user.favorite_tweets
    @comments = @user.comments
    @currentUserEntry = Entry.where(user_id: current_user.id)
    @userEntry = Entry.where(user_id: @user.id)
    unless @user.id == current_user.id
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      unless @isRoom
        @room = Room.new
        @entry = Entry.new
      end
    end
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_path
  end

  def follows
    user = User.find(params[:id])
    @users = user.following
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/relationsips_helper.rb
module RelationsipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/rooms/show.html.erb
<div class="container color-box">
  <h1>DM</h1>
  <h4>参加者</h4>
  <% @entries.each do |e| %>
    <h5><strong><%= link_to e.user.email, user_path(e.user.id) %></strong></h5>
  <% end %>
  <hr>
  <% if @messages.present? %>
    <% @messages.each do |m| %>
      <strong><%= m.content %></strong>
      <small>by<strong><%= link_to m.user.name, user_path(m.user.id) %></strong></small>
    <% end %>
  <% else %>
    <h3 class="text-center">メッセージはまだありません。</h3>
  <% end %>
  <%= form_for @message do |f| %>
    <%= f.text_field :content, placeholder: "メッセージを入力してください。", size: 70 %>
    <%= f.hidden_field :room_id, value: @room.id %>
    <br>
    <%= f.submit "送信", class: "btn btn-outline-warning" %>
  <% end %>
</div>

app/views/users/followers.html.erb
<div class="container color-box">
  <h1>User followers</h1>
<% @users.each do |user| %>
  <hr>
  <p><span>名前： </span><%= link_to user.name, user_path(user.id) %></p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
    <% else %>
      <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/users/follows.html.erb
<div class="container color-box">
  <h1>User following</h1>
<% @users.each do |user| %>
  <hr>
  <p><span>名前： </span><%= link_to user.name, user_path(user.id) %></p>
  <% if current_user != user %>
    <% if user.followed_by?(current_user) %>
      <p><%=link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
    <% else %>
      <p><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
    <% end %>
  <% end %>
<% end %>
</div>

app/views/users/index.html.erb
<div class="container color-box">
  <h1>ユーザー一覧</h1>

  <% @users.each do |user| %>
    <hr>
    <p><%= link_to user.name, user_path(user.id) %></p>
    <% if current_user != user %>
      <% if user.followed_by?(current_user) %>
        <p><%= link_to "フォロー中", user_relationships_path(user.id), method: :delete %></p>
      <% else %>
        <p><%= link_to "フォローする", user_relationships_path(user.id), method: :post %></p>
      <% end %>
    <% end %>
    <% if current_user.admin? %>
      <%= link_to "削除", user_path(user.id), method: :delete, data: {confirm: "本当に消しますか？"} %>
    <% end %>
  <% end %>
  <%= paginate @users %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<!--<%- if controller_name != 'sessions' %>
  <%#= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>-->

<!--<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "新規登録", new_registration_path(resource_name) %><br />
<% end %>-->

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <p>パスワードを忘れた場合は
    <%= link_to "こちら", new_password_path(resource_name) %><br />
  </p>
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<div class="container color-box">
<p class="notice"><%= notice %></p>
  <h1>ユーザー情報</h1>

<hr>
<h5><span>名前：</span><%= @user.name %></h5>
<% if current_user == @user %>
  <h5><span>メールアドレス：</span><%= @user.email %></h5>
<% else %>
  <% if @isRoom == true %>
    <p><%= link_to "DMする", room_path(current_user.id), class: "btn-outline-warning" %></p>
  <% else %>
    <%= form_for @room do |f| %>
      <%= fields_for @entry do |e| %>
        <%= e.hidden_field :user_id, value: @user.id %>
      <% end %>
      <%= f.submit "DMする", class: "btn btn-outline-warning" %>
    <% end %>
  <% end %>
<% end %>
<p><%= link_to "#{@user.following.count}フォロー", follows_user_path(@user.id) %></p>
<p><%= link_to "#{@user.followers.count}フォロワー",  followers_user_path(@user.id) %></p>
<% if current_user != @user %>
  <% if @user.followed_by?(current_user) %>
    <p><%= link_to "フォロー中", user_relationships_path(@user.id), method: :delete %></p>
  <% else %>
    <p><%= link_to "フォローする", user_relationships_path(@user.id), method: :post %></p>
  <% end %>
<% end %>
<% if current_user.admin? %>
  <%= link_to "削除", user_path(@user.id), method: :delete, data: {confirm: "本当に消しますか？"} %>
<% end %>

<h3>ツイート一覧</h3>
<hr>
<% @tweets.each do |tweet| %>
  <p><%= link_to tweet.body, tweet_path(tweet.id) %></p>
  <% if current_user.admin? %>
    <%= link_to "削除", tweet_path(@user.id), method: :delete, data: {confirm: "本当に消しますか？"} %>
  <% end %>
<% end %>
<h3>ファボツイート一覧</h3>
<hr>
<% @favorite_tweets.each do |tweet| %>
  <p><%= link_to tweet.body, tweet_path(tweet.id) %></p>
<% end %>
<h3>コメント一覧</h3>
<hr>
<% @comments.each do |comment| %>
  <p><%= link_to comment.body, tweet_path(comment.tweet.id) %></p>
<% end %>


</div>