config/routes.rb
Rails.application.routes.draw do
  get 'searches/user'
  get 'searches/tweet'

  # get 'home/index'
  # get 'home/show'
  root 'home#index'
  devise_for :users
  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    resource :comments, only: [:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :messages, only: [:create]

  resources :rooms, only: [:create, :show]
end
  

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  # def search(search)
  #   if search
  #     User.where(['name LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end

  # def Tsearch(search)
  #   if search
  #     Tweet.where(['body LIKE ?', "%#{search}%"])
  #   else
  #     all
  #   end
  # end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  validates :tweet_id, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :tweet

  validates :tweet_id, presence: true
  validates :user_id, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :comments, dependent: :destroy
  mount_uploader :image, ImageUploader

  validates :body, presence: true, length: {maximum: 140}
  validates :user_id, presence: true
  default_scope -> {order(created_at: :desc)}

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['body LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_tweets, through: :favorites, source: :tweet
  has_many :comments, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :following, through: :active_relationships, source: :follower
  has_many :followers, through: :passive_relationships, source: :following

  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  validates :name, presence: true

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationsips_helper.rb
module RelationsipsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>DeviseSample</title>
    <%= csrf_meta_tags %>
    <%# フォントのリンク %>
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar">
      <div class="container">
        <nav>
          <ul class="nav">
            <% if user_signed_in? %> 
              <li class="newpost-nav"><%= link_to "新規投稿", new_tweet_path %></li>
              <li class="mypage-nav"><%= link_to "マイページ", user_path(current_user) %></li>
              <li class="tweets-nav"><%= link_to "ツイート一覧", tweets_path %></li>
              <li class="users-nav"><%= link_to "ユーザー一覧", users_path %></li>
              <li class="profile-nav"><%= link_to 'プロフィール変更', edit_user_registration_path %></li>
              <li class="logout-nav"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="signin-nav"><%= link_to "サインイン", new_user_registration_path %></li>
              <li class="login-nav"><%= link_to "ログイン", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
        <% if user_signed_in? %>
          <div class="search">
            <%= form_tag(searches_user_path, method: :get) do %>
              <%= text_field_tag :search %>
              <%= submit_tag 'ユーザー検索', :name => nil, class: "btn btn-outline-warning search-user-btn" %>
            <% end %>
            <%= form_tag(searches_tweet_path, method: :get) do %>
              <%= text_field_tag :tweet %>
              <%= submit_tag 'ツイート検索', :body => nil, class: "btn btn-outline-warning" %>
            <% end %>
          </div>
        <% end %>
      </div>
    </header>
    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>